name: Install Node.js, npm, and Yarn
description: Runs `actions/setup-node` and installs unplugged dependencies with Yarn.
author: Steffen Diswal
runs:
  using: composite
  steps:
    # While `actions/checkout` is also a common step, it must be declared separately in every job.
    # Otherwise, the GitHub Actions runner won't be able to locate this `action.yml` file.
    - name: Install Node.js, npm, and Yarn
      uses: actions/setup-node@v4 # https://github.com/actions/setup-node
      with:
        cache: yarn
        node-version: 20
    - name: Install unplugged dependencies
      run: yarn install --immutable
      shell: bash
