name: Revalidate build artifacts
description: Rebuilds the project to update the build artifacts in the workflow cache.
author: Steffen Diswal

runs:
  using: composite
  steps:
    - name: Restore the build artifacts
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # https://github.com/actions/cache/releases/tag/v3.3.2 (pinned to the commit SHA)
      with:
        path: ./dist/
        key: ${{ runner.os }}-build-artifacts-${{ hashFiles('src/**', 'package.json', 'vite.config.ts', 'yarn.lock') }}
      id: cache-build-artifacts
    - name: Install Yarn and third-party dependencies
      if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
      uses: ./.github/actions/yarn-zero-install-cache
    - name: Rebuild the project
      if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
      run: yarn run build
