name: pnpm
description: Installs pnpm and third-party dependencies.

# All third-party actions are pinned to a specific commit SHA for security reasons.
# https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      #
    - name: Install Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        cache: pnpm
        node-version-file: ./.nvmrc
        registry-url: https://registry.npmjs.org
      #
    - name: Install third-party dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
