name: Continuous integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate-static-types:
    name: Static types (TypeScript)
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4 # https://github.com/actions/checkout
      - name: Prepare Node.js, npm, and Yarn
        uses: ./.github/actions/node-prepare
      - name: Validate
        run: yarn run validate.types

  validate-code-format:
    name: Code format (Prettier)
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4 # https://github.com/actions/checkout
      - name: Prepare Node.js, npm, and Yarn
        uses: ./.github/actions/node-prepare
      - name: Validate
        run: yarn run validate.format

  validate-unit-tests:
    name: Unit tests (Vitest)
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4 # https://github.com/actions/checkout
      - name: Prepare Node.js, npm, and Yarn
        uses: ./.github/actions/node-prepare
      - name: Validate
        run: yarn run validate.test

  validate-commit-messages:
    name: Commit messages
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - name: Validate
        uses: rainstormy/github-action-validate-commit-messages@v1 # https://github.com/rainstormy/github-action-validate-commit-messages
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          rules: acknowledged-author-email-addresses, acknowledged-author-names, acknowledged-committer-email-addresses, acknowledged-committer-names, capitalised-subject-lines, empty-line-after-subject-lines, imperative-subject-lines, limit-length-of-body-lines, limit-length-of-subject-lines, multi-word-subject-lines, no-co-authors, no-merge-commits, no-revert-revert-commits, no-squash-commits, no-trailing-punctuation-in-subject-lines, no-unexpected-whitespace, unique-subject-lines
          acknowledged-author-email-addresses--patterns: '\d+\+.+@users\.noreply\.github\.com'
          acknowledged-author-names--patterns: '\p{Lu}.*\s.+'
          acknowledged-committer-email-addresses--patterns: '\d+\+.+@users\.noreply\.github\.com'
          acknowledged-committer-names--patterns: '\p{Lu}.*\s.+'
