name: Initiate release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The semantic version number of the new release.
        type: string
        required: true

jobs:
  create-release-branch-and-pull-request:
    name: Create release branch and pull request
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4 # https://github.com/actions/checkout
      - name: Install Node.js, npm, and Yarn
        uses: ./.github/actions/install-node-npm-yarn
      - name: Generate build artifacts
        run: yarn run build
      - name: Prepare the release
        run: yarn run release.prepare "${RELEASE_VERSION}"
        env:
          RELEASE_VERSION: ${{ github.event.inputs.version }}
      - name: Use Nimbus (Bot) in Git
        uses: ./.github/actions/git-config-user-rainstormybot-nimbus
        with:
          bot-nimbus-ssh-public-key: ${{ secrets.BOT_NIMBUS_SSH_PUBLIC_KEY }}
          bot-nimbus-ssh-the-private-key: ${{ secrets.BOT_NIMBUS_SSH___THE___PRIVATE___KEY }}
          ssh-key-fingerprints-github: ${{ secrets.SSH_KEY_FINGERPRINTS_GITHUB }}
      - name: Create a release branch
        run: git checkout -b "release/${RELEASE_VERSION}"
        env:
          RELEASE_VERSION: ${{ github.event.inputs.version }}
      - name: Stage and commit modified files
        run: |
          git add CHANGELOG.adoc package.json
          git commit --message "Prepare the release of ${RELEASE_VERSION}"
          git push --set-upstream origin "release/${RELEASE_VERSION}"
        env:
          RELEASE_VERSION: ${{ github.event.inputs.version }}
      - name: Fetch the main branch
        run: git fetch origin main # See https://github.com/cli/cli/issues/5896.
      - name: Create a pull request from the release branch
        run: |
          gh auth login --with-token <<< "${BOT_NIMBUS_GH_AUTH_TOKEN}"
          gh pr create --base main --title "Release ${RELEASE_VERSION}" --body "This pull request was automatically created by the \`release-1-initiate\` workflow in GitHub Actions."
        env:
          BOT_NIMBUS_GH_AUTH_TOKEN: ${{ secrets.BOT_NIMBUS_GH_AUTH_TOKEN }}
          RELEASE_VERSION: ${{ github.event.inputs.version }}
