# This workflow publishes the package to the npm registry.
#
# It is triggered automatically by pushing a Git tag with a `v` prefix, as done by the `release-tag.yml` workflow.
#
# It can be triggered manually via the GitHub CLI:
#   gh workflow run release-npm.yml --ref <tag-name>
#   gh run watch
#
# It can be triggered manually via the GitHub web interface:
#   https://github.com/rainstormy/updraft/actions/workflows/release-npm.yml

name: Release / npm

on:
  push:
    tags:
      - v*
  workflow_dispatch:

# Cancel all previous runs of this workflow that are still in progress on the same branch.
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: release-npm-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# All third-party actions are pinned to a specific commit SHA for security reasons.
# https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
jobs:
  quality-assurance:
    name: Quality assurance
    permissions:
      contents: read # Allow the job to call the reusable `ci.yml` workflow.
      pull-requests: read # `ci.yml` requires `pull-requests` read permissions.
    uses: ./.github/workflows/ci.yml

  npm-package:
    name: npm package
    needs: quality-assurance
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    permissions:
      contents: read # Allow the job to check out the repository.
      id-token: write # Allow npm to publish the package with provenance.
    steps:
      - name: Check out the repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        #
      - name: Restore build artifacts
        uses: ./.github/actions/build-artifacts
        #
      - name: Install pnpm and third-party dependencies
        uses: ./.github/actions/pnpm
        #
      - name: Publish the package to npm
        uses: rainstormy/release/npm@eb87dc4ba5e9e89451adce4a3c62538e5ecef809 # v1.1.1
        with:
          access-level: public
          npm-auth-token: ${{ secrets.BOT_NIMBUS_NPM_TOKEN }}
          packagejson-excluded-fields: |
            packageManager
            scripts
            // dependencies
            // devDependencies
