# This workflow creates a release commit and a pull request towards the `main` branch.
#
# It can be triggered manually on any branch via the GitHub CLI:
#
#   gh workflow run release.yml --field version=<major.minor.patch[-prerelease][+buildinfo]> [--ref <branch-name>]
#   gh run watch
#
# It can be triggered manually via the GitHub web interface:
#   https://github.com/rainstormy/updraft/actions/workflows/release.yml

name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The semantic version number of the new release.
        type: string
        required: true

run-name: ${{ inputs.version }}

# Cancel all previous runs of this workflow that are still in progress on the same branch.
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# All third-party actions are pinned to a specific commit SHA for security reasons.
# https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
jobs:
  validate-software-quality:
    name: Validate software quality
    permissions:
      contents: read # Allow the job to call the reusable `ci.yml` workflow.
      pull-requests: read # `ci.yml` requires `pull-requests` read permissions.
    uses: ./.github/workflows/ci.yml

  create-pull-request:
    name: Create pull request
    needs: validate-software-quality
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    permissions: { }
    steps:
      - name: Check out the repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # https://github.com/actions/checkout/releases/tag/v4.1.1
        with:
          # Use a separate access token with permission to commit and push.
          token: ${{ secrets.BOT_NIMBUS_GH_AUTH_TOKEN }}
        #
      - name: Restore build artifacts
        uses: ./.github/actions/build-artifacts
        #
      - name: Install pnpm and third-party dependencies
        uses: ./.github/actions/pnpm
        #
      - name: Update release artifacts
        # Run the newest version of Updraft on itself.
        # Use double quotes to enclose a space-separated list of files to ensure correct shell expansion.
        # language=sh
        run: |
          VERSION=$(echo "$RAW_VERSION" | grep --only-matching --extended-regexp '[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?')
          if [[ "$VERSION" == *'-'* || "$VERSION" == *'+'* ]]; then
            FILES="package.json"
          else
            FILES="CHANGELOG.adoc package.json"
          fi
          node ./src/entry.cli.js --files $FILES --release-version $VERSION
        env:
          RAW_VERSION: ${{ inputs.version }}
        #
      - name: Use Nimbus (Bot) in Git
        uses: rainstormy-actions/rainstorm-release/bot-nimbus@0acf7e891a6a3db23bea2d429aea04434c0f42f3 # https://github.com/rainstormy-actions/rainstorm-release
        with:
          bot-nimbus-ssh-public-key: ${{ secrets.BOT_NIMBUS_SSH_PUBLIC_KEY }}
          __bot-nimbus-ssh-private-key__: ${{ secrets.BOT_NIMBUS_SSH___THE___PRIVATE___KEY }}
          ssh-key-fingerprints-github: ${{ secrets.SSH_KEY_FINGERPRINTS_GITHUB }}
        #
      - name: Create a release pull request
        uses: rainstormy-actions/release/pr@0245a6b2708a91d0c8f4f22e8c6d321d4fc8c580 # https://github.com/rainstormy-actions/release
        with:
          gh-auth-token: ${{ secrets.BOT_NIMBUS_GH_AUTH_TOKEN }}
          version: ${{ inputs.version }}
